CREATE TABLE IF NOT EXISTS SALESMAN(
    SALESMAN_ID INTEGER,
    NAME TEXT,
    CITY TEXT,
    COMMISSION TEXT);

DELETE FROM SALESMAN;
INSERT INTO SALESMAN(SALESMAN_ID,NAME,CITY,COMMISSION) VALUES
    (0001, "JOHN", "PARIS", "0.15"),
    (0002, "HENRY", "MUMBAI", "0.12"),
    (0003, "JOE", "VANCOUVER", "0.10"),
    (0004, "LISA", "BIRMINGHAM", "0.15"),
    (0005, "JEFF", "LONDON", "0.13");

CREATE TABLE IF NOT EXISTS CUSTOMER(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME TEXT,
    CITY TEXT,
    SALESMAN_ID INTEGER);

DELETE FROM CUSTOMER;
INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, CITY, SALESMAN_ID) VALUES
    (001, "BRIAN", "PARIS", 0001),
    (002, "STACY", "LONDON", 0005),
    (003, "MARK", "BIRMINGHAM", 0004),
    (004, "ARTHUR", "MUMBAI", 0002),
    (005, "GINA", "VANCOUVER", 0003);

CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_NO INTEGER,
    PURCHASE_AMOUNT TEXT,
    CUSTOMER_ID INTEGER,
    SALESMAN_ID INTEGER);

DELETE FROM ORDERS;
INSERT INTO ORDERS(ORDER_NO, PURCHASE_AMOUNT, CUSTOMER_ID, SALESMAN_ID) VALUES
    (001, "4", 001, 0001),
    (002, "6", 003, 0004),
    (003, "9", 002, 0005),
    (004, "20", 005, 0003),
    (005, "10", 004, 0002);

SELECT CUSTOMER.CUSTOMER_NAME, SALESMAN.NAME, SALESMAN.CITY FROM CUSTOMER JOIN SALESMAN ON CUSTOMER.CITY = SALESMAN.CITY;
    
SELECT CUSTOMER.CUSTOMER_NAME, SALESMAN.NAME FROM CUSTOMER JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID;

SELECT ORDERS.ORDER_NO, CUSTOMER.CUSTOMER_NAME FROM ORDERS JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = ORDERS.CUSTOMER_ID;

SELECT CUSTOMER.CUSTOMER_NAME AS CUSTOMER, CUSTOMER.CITY AS CITY, SALESMAN.NAME AS SALESMAN, SALESMAN.COMMISSION AS COMMISSION FROM CUSTOMER JOIN SALESMAN ON CUSTOMER.SALESMAN_ID = SALESMAN.SALESMAN_ID WHERE SALESMAN.COMMISSION BETWEEN 0.12 AND 0.14;
