--1)Write a SQL query that finds the number of products. 
--2)Write a SQL query that finds the average price of all products. 
--3)Write a SQL query that finds the sum of the price of all products.
CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    PRODUCT_SALES INTEGER,
    PRODUCT_STOCK INTEGER
);
    DELETE FROM PRODUCT;
    INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,PRODUCT_SALES,PRODUCT_STOCK) VALUES
    ("0001", "RED SHIRT", 40, 60),
    ("0002", "BLUE SHIRT", 70, 30),
    ("0003", "BLACK SHIRT", 150, 50),
    ("0004", "WHITE SHIRT", 74, 126),
    ("0005", "GREEN SHIFT", 40, 60);

SELECT PRODUCT_NAME, PRODUCT_SALES FROM PRODUCT;
SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT FROM PRODUCT;
SELECT AVG(PRODUCT_SALES) AS PRODUCT_AVERAGE FROM PRODUCT;
SELECT SUM(PRODUCT_STOCK) AS PRODUCTS_IN_STOCK FROM PRODUCT;