CREATE TABLE IF NOT EXISTS PRODUCTS(
    ID TEXT PRIMARY KEY,
    NAME TEXT,
    PRICE INTEGER,
    NUMBER INTEGER
);

INSERT INTO PRODUCTS(ID,NAME,PRICE,NUMBER) VALUES
    ("0001","KEYBOARD",18,500),
    ("0002","MOUSE",6,1000),
    ("0003","WIRES",6,1000),
    ("0004","MONITOR",25,500);

SELECT NAME,PRICE FROM PRODUCTS;

SELECT NAME,PRICE FROM PRODUCTS WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS);

SELECT NAME,PRICE FROM PRODUCTS WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS);

SELECT MIN(PRICE) FROM PRODUCTS;

SELECT NAME,MIN(PRICE) FROM PRODUCTS;



