CREATE TABLE IF NOT EXISTS NOBEL_WIN(
    SUBJECT TEXT,
    WINNER TEXT,
    YEAR INTEGER,
    COUNTRY TEXT,
    CATAGORY TEXT);
DELETE FROM NOBEL_WIN;
INSERT INTO NOBEL_WIN(SUBJECT,WINNER,YEAR,COUNTRY,CATAGORY) VALUES
("MATHEMATICS", "PAUL", 1986, "USA", "MATHS"),
("PHYSICS", "HUGH", 1997, "MEXICO", "SCIENTIST"),
("PHYSHOLOGY", "ALEX", 2003, "FRANCE", "PHYSHOLOGIST"),
("MATHEMATICS", "JOHN", 1995, "GERMANY", "MATHS"),
("CHEMISTRY", "HAMILTON", 1973, "SWEDEN", "LINGUIST"),
("PHYSICS", "NEIL", 2011, "USA", "SCIENTIST");

SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE "P%";
SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE "%S";
